title: "Nick Lieurance - Woodward Technical Writer"
description: "A plan for my first 90 days"
url: "https://nlieurance.github.io"
baseurl: "/Woodward/"  # For user/organization sites; for project sites use "/repo-name"

remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
