title: "Nick Lieurance - Woodward Technical Writer"
description: "A plan for my first 90 days"
url: "https://nlieurance.github.io"
baseurl: "/Woodward/"  # For user/organization sites; for project sites use "/repo-name"

theme: Slate theme   # Or another supported theme
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
